name       : pitivi
version    : '2021.01'
homepage   : http://www.pitivi.org/
release    : 18
source     :
    - https://download.gnome.org/sources/pitivi/2021/pitivi-2021.01.tar.xz : 818946f9aaf7347f901e0cb445819711dd518d62519caa17e475ec1476d63f4f
license    : LGPL-2.1-or-later
component  : multimedia.video
summary    : Editor for audio/video projects using the GStreamer framework
description: |
    Pitivi is a Free video editor with a beautiful and intuitive user interface, a clean codebase and a fantastic community
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - itstool
    - numpy
rundeps    :
    - gsound
    - gst-python
    - gstreamer-1.0-plugins-bad
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - gstreamer-editing-services
    - matplotlib
    - numpy
    - python3-cairo
    - pycanberra
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
