name       : pitivi
version    : 0.95
homepage   : http://www.pitivi.org/
release    : 5
source     :
    - https://download.gnome.org/sources/pitivi/0.95/pitivi-0.95.tar.xz : 5f15220bcc3d02cef4edacaa19da284014caf725e41fc9cbec70469582e1d313
license    : LGPL-2.1
component  : multimedia.video
summary    : Editor for audio/video projects using the GStreamer framework
description: |
    Editor for audio/video projects using the GStreamer framework
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gl)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(py3cairo)
    - pkgconfig(python-3.5)
    - gnome-doc-utils
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - itstool
    - numpy
rundeps:
    - gnonlin
    - gstreamer-1.0
    - gstreamer-editing-services
    - gst-python
    - numpy
    - python3-cairo
    - matplotlib
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
