name       : pitivi
version    : '0.99'
homepage   : http://www.pitivi.org/
release    : 8
source     :
    - https://download.gnome.org/sources/pitivi/0.99/pitivi-0.99.tar.xz : c9d02fd669801e0de94b5ca06179da6e8a7e1cb666b843fc12df6f0632db8f7c
license    : LGPL-2.1
component  : multimedia.video
summary    : Editor for audio/video projects using the GStreamer framework
description: |
    Pitivi is a Free video editor with a beautiful and intuitive user interface, a clean codebase and a fantastic community
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gl)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gst-transcoder-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(py3cairo)
    - pkgconfig(python-3.5)
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - itstool
    - numpy
rundeps    :
    - gst-python
    - gst-transcoder
    - gstreamer-1.0
    - gstreamer-editing-services
    - matplotlib
    - numpy
    - python3-cairo
    - pycanberra
setup      : |
    export LC_ALL=en_US.utf8
    %meson_configure
build      : |
    export LC_ALL=en_US.utf8
    %meson_build
install    : |
    export LC_ALL=en_US.utf8
    %meson_install
