name       : pitivi
version    : 0.999
homepage   : http://www.pitivi.org/
release    : 15
source     :
    - https://download.gnome.org/sources/pitivi/0.999/pitivi-0.999.tar.xz : cb6f8a831383e698c2117ca7caec77b8167a6b2e2b0fb9c375e6a4f7c815b757
license    : LGPL-2.1-or-later
component  : multimedia.video
summary    : Editor for audio/video projects using the GStreamer framework
description: |
    Pitivi is a Free video editor with a beautiful and intuitive user interface, a clean codebase and a fantastic community
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(cairo)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gl)
    - pkgconfig(gobject-introspection-1.0)
    - pkgconfig(gst-editing-services-1.0)
    - pkgconfig(gst-transcoder-1.0)
    - pkgconfig(gst-validate-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libpulse)
    - pkgconfig(py3cairo)
    - pkgconfig(python3)
    - gstreamer-1.0-libav
    - gstreamer-1.0-plugins-good
    - gstreamer-1.0-plugins-ugly
    - itstool
    - numpy
rundeps    :
    - gsound
    - gst-python
    - gst-transcoder
    - gstreamer-1.0
    - gstreamer-editing-services
    - matplotlib
    - numpy
    - python3-cairo
    - pycanberra
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
